### PR TITLE
Use similar wording to gsd and hoomd (half axis)

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

Use the wording of wikipedia at https://en.wikipedia.org/wiki/Ellipsoid#Standard_equation in the documentation

## Motivation and Context

[Hoomd uses the wording "half-axis"](https://hoomd-blue.readthedocs.io/en/latest/module-hpmc-integrate.html#hoomd.hpmc.integrate.Ellipsoid.shape)
[GSD just uses "radius in _ direction"
](https://gsd.readthedocs.io/en/stable/shapes.html#ellipsoids)
## Types of Changes

- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

### CODE REVIEW

**Review by Tobias-Dwyer — CHANGES_REQUESTED** [review]
This is good, thanks for updating these, except I think it's principal not principle.

**Comment by cbkerr** [comment]
oops, thanks, fixed!

**Review by Tobias-Dwyer — APPROVED** [review]
This looks correct!

**Comment by vyasr** [comment]
Thanks!

**Pull request merged**
