### PR TITLE
Added shape families for many new solids, functions to return polyhedron edges, and bug fixes.

### PR DESCRIPTION
**Pull request by janbridley**
### Added
- Shape families and stored data for Archimedean, Catalan, and Johnson solids.
- Shape family and stored data for n-gonal prisms and antiprisms up to n=10.
- Shape family and stored data for equilateral pyramids and dipyramids.
- All new solids are normalized to an edge length of one.
- New class that returns the endpoints of edges on a polyhedron.

### Changed
- Increased precision of stored data for ``PlatonicFamily`` solids.
- PlatonicFamily solids are now normalized to an edge length of one.

### Fixed
- Issue with certain polyhedra requiring ``merge_faces()`` to be represented accurately.
- Issue where ``repr`` would fail for solids with more than one face type.
- ``gsd_shape_spec`` property of the Polyhedron class now returns a correctly keyed GSD dict. (#167)

## Motivation and Context
Querying polyhedra other than Platonic solids could be relatively difficult. This release adds shape families similar to ``PlatonicFamily`` for Archimedean, Catalan, Johnson and other solids. In addition, edges of polyhedra needed to be calculated from data in ``Polyhedron.faces``: this feature is now built into the package. ``Polyhedron.edges`` returns the endpoints of each edge in vertex index form (similar to ``Polyhedron.faces``) and ``Polyhedron.get_edge_vectors`` returns each endpoint as coordinates in 3D space.

## Types of Changes
- [x] Documentation update
- [x] Bug fix
- [x] New features

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/coxeter/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/coxeter/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] I have updated the [changelog](https://github.com/glotzerlab/coxeter/blob/master/ChangeLog.txt) and the [credits](https://github.com/glotzerlab/coxeter/blob/master/doc/source/credits.rst).

### CODE REVIEW

**Review by vyasr — CHANGES_REQUESTED** [review]
@janbridley thanks for this contribution! There is a lot of good stuff in here, but a few big comments as well:
- This PR contains a large number of unrelated changes. Could you please make separate PRs? Some of them can be lumped together, but others really have no relationship and should be separated. This is important because when a PR is merged, all of the commits are squashed into a single one. On the main branch, we want to be able to see each change atomically associated with a single commit. Separating each related set of changes into one PR ensures that the commits on the main branch are usable in this way. Moreover, keeping all changes in a PR tightly related is helpful for reviewers. From a quick look, I would expect separate PRs for:
  1. Adding new shape families
  2. Changing the shape family normalizations and increasing the precision of the stored values.
  3. Fixing merge_faces.
  4. Fixing repr 
  5. Fixing #167 
-  We do not change the release in feature PRs. Once a sufficient number of PRs have been made, package maintainers will make a decision that it is time for a release, at which point all of the changes up to that point will be evaluated to determine the type of the release (major, minor, or patch, depending on whether there are any API-breaking changes or new features). Each of the PRs that I suggest above should be made without changing the release number. Once they are completed, you should talk to @Tobias-Dwyer about making a release, and he can walk you through that process if he thinks the package is in a good place for a new version.
- There are a number of temporary files committed here that should not be. I see .DS_Store files from your Mac and a .coverage file from running test coverage locally. I also see changes to the paper Figure1.ai file. All of these changes should be removed.

Unrelated to your PR, it seems like coxeter CI is broken. @b-butler I see that the last commit on master was a testing-related commit without a PR, did you intend to add that or was that accidental? In any case, it also looks like CI has been broken since the [last pre-commit update](https://github.com/glotzerlab/coxeter/commit/9cb98bbe3558b1070fc19d44227fd13fb5079b35), although the problem doesn't look related to that. Could you or @Tobias-Dwyer have a look at unblocking CI? We want CI running before merging any new PRs.

**Comment by b-butler** [comment]
@vyasr yeah that was an accident. It doesn't break anything nor completely fix it. I just haven't gotten around to fixing it yet.

**Comment by bdice** [comment]
@b-butler @vyasr I added branch protections to `master` to prevent pushing without a PR and to require passing CI checks. I'll open a quick PR to fix CI now.

**Comment by bdice** [comment]
I opened https://github.com/glotzerlab/coxeter/pull/175 to fix the failing CI. If someone is able to review/approve/merge, feel free. Hope that helps.

**Comment by janbridley** [comment]
All changes made in this PR have been incorporated into other PRs as requested. This will now be closed.

**Pull request closed without merging**
